---
title: "function"
output: html_document
date: "2023-02-27"
---

```{r setup, include=FALSE}
library(tidyverse)
library(NMF)
library(Seurat)
library(Matrix)
library(topGO)
library(reshape2)
library(pheatmap)
library(RColorBrewer)
```

## read data
```{r}
readmatrix = function(dir){
  genefile <- paste0(dir,"/features.tsv.gz")
  barcodefile <- paste0(dir,"/barcodes.tsv.gz")
  matrixfile <- paste0(dir,"/matrix.mtx.gz")   
  gn <- read.table(genefile,as.is=T)
  cn <- readLines(barcodefile)
  matrix <- as.matrix(readMM(matrixfile))
  rownames(matrix) = gn$V2
  colnames(matrix) = cn
  matrix
}
dir = '/Users/tianchuangao/Desktop/kidney/1287'
matrix_1287 = readmatrix(dir)
```

## data process
```{r}
data_process= function(x){
  x = as.data.frame(x)
  # removed cells less than 2,500 genes were detected
  x = x[colSums(x>0)>2500]
  # remove cells that below threshold
  threshold = mean(colSums(x>0))-2*sd(colSums(x>0))
  x = x[colSums(x>0)>threshold]
  # excluded genes with Ea<4
  tpm = (2^x-1)*10
  Ea=log2(rowMeans(replace(tpm, tpm == 0, NA), na.rm = TRUE)+1)
  Ea = as.data.frame(Ea)
  row_index=which(Ea$Ea>4)
  x = x[row_index,]
  # centering
  x=sweep(x,1,rowMeans(x))
}
```

## rank selection
proposed to take the first value of r for which the cophenetic coefficient starts decreasing, 
```{r}
load('1287.RData')
sj516 = read.table("~/Desktop/medulloblastoma/tumour_data/GSM3905424_SJ516.txt")
sj516 = data_process(sj516)
sj516[sj516<0]=0.000001
estimate$measures
plot(estimate)
V.random <- randomize(sj516)
estim.r.random <- nmf(V.random, 2:5, nrun=10, seed=123456)
estimate = nmf(sj516, rank=2:5, method="brunet", nrun=10, seed=123)
plot(estimate)
rank_selection = function(matrix,a,b){
  estimate = nmf(matrix, rank=a:b, method="brunet", nrun=10, seed=123)
  diff = c(diff(estimate$measures$cophenetic),NA)
  coph = data.frame(estimate$measures$rank, diff)
  coph %>%
    filter(diff < 0) %>%
    head(n=1) %>%
    pull(estimate.measures.rank)
  
  }
rank_selection(sj516,2,5)
```

## nmf process
```{r}
nmf_process = function(matrix,rank,method){
  result = nmf(matrix, rank = rank,method = method)
  fs = extractFeatures(result,30L)
  fs = lapply(fs,function(x)rownames(result)[x])
  fs
}
a = nmf_process(matrix = sj516, rank = 4, method = "brunet")
```

## GO Analysis
```{r}

allgene = rownames(sj516)
  diffgene = a

res1 = GOenrich(allgene = rownames(sj516), diffgene = a[[1]])
res2 = GOenrich(allgene = rownames(sj516), diffgene = a[[2]])
res3 = GOenrich(allgene = rownames(sj516), diffgene = a[[3]])
res4 = GOenrich(allgene = rownames(sj516), diffgene = a[[4]])

res <- list(res1,res2,res3,res4)
names(res) <- c(1,2,3,4)
res[4]=sigres


```


## figure 1
```{r}
# correlation
data_process_1= function(x){
  x = as.data.frame(x)
  x = x[colSums(x>0)>2500]
  threshold = mean(colSums(x>0))-2*sd(colSums(x>0))
  x = x[colSums(x>0)>threshold]
  # excluded genes with Ea<4
  tpm = (2^x-1)*10
  Ea=log2(rowMeans(replace(tpm, tpm == 0, NA), na.rm = TRUE)+1)
  Ea = as.data.frame(Ea)
  row_index=which(Ea$Ea>4)
  x = x[row_index,]
}
sj577 = read.table("~/Desktop/medulloblastoma/tumour_data/GSM3905425_SJ577.txt")
sj577 = data_process_1(sj577)
sj577 = (sj577-rowMeans(sj577))/apply(sj577, 1, sd)
summary(sj577[1,])

cm <- cor(sj577)
max_2 = max(cm[cm != max(cm)])
cm[cm==1]=max_2
cm = rescale(cm, to= c(-0.1,0.2))

pheatmap(cm, 
         clustering_distance_rows = "correlation", 
         clustering_distance_cols = "correlation",
         cluster_cols = TRUE,
         cluster_rows = TRUE,
         show_rownames=F,
         show_colnames=F,
         filename = "correlation.pdf",
         color = colorRampPalette(c("blue","green","yellow","red"))(100))
# PCA
pcRes <- prcomp(t(sj577),rank. = 8)
autoplot(pcRes, 
         colour="blue")
pcRes$x[, ]
pheatmap(pcRes$x[, ],
         show_rownames=F,
         filename = "pca.pdf")

# nmf meta program
sj577 = data_process(sj577)
sj577[sj577<0]=0.000001
res = nmf(sj577, rank = 3)
fs = extractFeatures(res,30L)
fs = lapply(fs,function(x)rownames(res)[x])
coefmap(res,filename= "nmf.pdf")
```

